GO
CREATE DATABASE cloud;
GO

GO
USE cloud;
GO

GO
CREATE TABLE Account(
	ID INT PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(25) NOT NULL CHECK(LEN(FirstName) >= 3),
	LastName VARCHAR(25) NOT NULL CHECK(LEN(LastName) >= 3),
	Email VARCHAR(35) UNIQUE NOT NULL CHECK(Email LIKE '%@%'),
	HashedPassword VARCHAR(64) NOT NULL,
	Registered DATE NOT NULL DEFAULT (FORMAT (GETDATE(), 'yyyy-MM-dd'))
);
GO

GO
CREATE TABLE FolderColor(
	ID INT PRIMARY KEY IDENTITY(1,1),
	ColorName VARCHAR(15) UNIQUE NOT NULL
);
GO

GO
CREATE TABLE Folder(
	ID INT PRIMARY KEY IDENTITY(1,1),
	FolderName VARCHAR(45) NOT NULL CHECK(LEN(FolderName) > 0),
	ColorID INT NOT NULL DEFAULT 1 FOREIGN KEY REFERENCES FolderColor(ID),
	IsShared BIT NOT NULL DEFAULT 0,
	CreatedAt DATE NOT NULL DEFAULT (FORMAT (GETDATE(), 'yyyy-MM-dd'))
);
GO

GO
CREATE TABLE Access(
	ID INT PRIMARY KEY IDENTITY(1,1),
	AccountID INT NOT NULL FOREIGN KEY REFERENCES Account(ID),
	FolderID INT NOT NULL FOREIGN KEY REFERENCES Folder(ID)
);
GO

GO
CREATE TABLE AttachmentType(
	ID INT PRIMARY KEY IDENTITY(1,1),
	TypeName VARCHAR(45) UNIQUE NOT NULL,
);

GO

GO
CREATE TABLE Attachment(
	ID INT PRIMARY KEY IDENTITY(1,1),
	FolderID INT NOT NULL FOREIGN KEY REFERENCES Folder(ID),
	TypeID INT FOREIGN KEY REFERENCES AttachmentType(ID),
	AttachmentName VARCHAR(20) NOT NULL CHECK(LEN(AttachmentName) > 0),
	SizeMB FLOAT NOT NULL,
	CreatedAt DATE NOT NULL DEFAULT (FORMAT (GETDATE(), 'yyyy-MM-dd')),
	UpdatedAt DATE NOT NULL DEFAULT (FORMAT (GETDATE(), 'yyyy-MM-dd')),
);